apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: mytodo
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS tododb;
    USE tododb;
    CREATE TABLE IF NOT EXISTS todos (
      id         INT AUTO_INCREMENT PRIMARY KEY,
      task       VARCHAR(500) NOT NULL,
      done       BOOLEAN DEFAULT FALSE,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    );
